version: "2"

run:
  timeout: 5m
  relative-path-mode: gomod

linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - durationcheck
    - gocheckcompilerdirectives
    - goprintffuncname
    - ineffassign
    - makezero
    - nolintlint
    - rowserrcheck
    - sqlclosecheck
